groups = [
    ["zli117","scui8"],
    ["bwzhou2","kalanad2"],
    ["yhung133","gliu18"],
    ["yuang5","basu9"],
    ["jyshnkr2","gotsis2"],
    ["bhavya2",None],
    ["usoylu2","berki2"],
    ["sjgupta2","kaucic2"],
    ["djrbrts2","houhaol2"],
    ["hthuynh2","runzel3"],
    ["dakowal2",None],
    ["lishu2","zhung2"],
    ["szhou36","xz2"],
    ["avinash9","jugatl2"],
    ["yuxinx2",None],
    ["kzou3","fengzex2"],
    ["chengd2","zibolin2"],
    ["sy15","bchhet2"],
    ["ywang505","Hxu58"],
    ["twu54","kz3"],
    ["tl6","swko2"],
    ["kk20","vr7"],
    ["uf2","ccheema2"],
    ["xiaoluq2","lujin2"],
    ["junruin2","yuexu8"],
    ["jchen259","tianyus2"],
    ["abh5","moeberg2"],
    ["iludden2","adithya5"],
    ["bz2","ezhuang2"],
    ["xilinyu2",None],
    ["ddalmas2","jshowel2"],
    ["pacole2","aachen3"],
    ["zwei17",None],
    ["anhleu2","hoelzel2"],
    ["rsun12","hkim326"],
    ["shunhan2","tianc2"],
    ["skim445","hjo8"],
    ["osneh2","colomb2"],
    ["amitmp2","va13"],
    ["banik","nanaras2"],
    ["bozheng2","cz28"],
    ["luc2",None],
    ["hornits2","jhan80"],
    ["hj19","srirams4"],
    ["juhitha2","kkim154"],
    ["pfliu2","haozey2"],
    ["mswisz2",None],
    ["gjounel2",None],
    ["xinyuh5","yingruc2"],
    ["aamirh2",None],
    ["romanch2",None],
    ["ruester2",None],
    ["rhuang22",None],
    ["bj2",None],
    ["yizhih3","zl50"],
    ["xiaotao2","jdrynld2"],
    ["junyeob2","rshe2"],
    ["srirams2","koiloth2"],
    ["wenting7",None],
    ["siyuliu3","szhou53"],
    ["avancha2","broper2"],
    ["ytayng2","reza2"],
    ["yujiaq3","xdu12"],
    ["emurray3",None],
    ["yuningx2",None],
]

def get_partner(netid):
    for group in groups:
        if group[0] == netid:
            return group[1]
        elif group[1] == netid:
            return group[0]
    return None
